#! /usr/bin/env python
"""
Program to put the test/*.json files into test.html.in, generating output on
stdout.

Copyright (c) 2012 Tommie Gannert
Distributed under the MIT license
"""

import json
import os.path
import sys

if __name__ == '__main__':
    with open(os.path.join(os.path.dirname(sys.argv[0]), 'test.html.in'), 'rt') as f:
        tmpl = f.read()

    tests = {}
    test_path = os.path.join(os.path.dirname(sys.argv[0]), '..', 'test')

    for filename in os.listdir(test_path):
        if not filename.endswith('.json'):
            continue

        with open(os.path.join(test_path, filename), 'rt') as f:
            tests[filename[:-5]] = json.load(f)

    JAVASCRIPT_TEMPLATE = '<script type="text/javascript">var TESTS = %s;</script>'

    sys.stdout.write(tmpl.replace('<?tests?>', JAVASCRIPT_TEMPLATE % (json.dumps(tests),)))
